service:
  http_port: 8088
  debug: true
  eino_debug: false
  stream_mode: true
  apmplus_app_key: "your_apmplus_app_key"
  apmplus_region: "cn-beijing"
  langfuse_public_key: ""
  langfuse_secret_key: ""
lark:
  app_id:
  app_secret:
llm:
  base_url:
  model:
  api_key:
embed:
  base_url:
  api_key:
  model:
indexer:
  redis_addr:
  redis_pwd:
  redis_prefix: "knowledge:doc:"
  index_name: "vector_index"
  dimension: 4096
  protocol: 2
