service:
  http_port: 8088
  stream_mode: true
lark:
  app_id:
  app_secret:
llm:
  model:
  api_key:
embed:
  base_url:
  api_key:
  model:
indexer:
  redis_addr:
  redis_pwd:
  redis_prefix: "knowledge:doc:"
  dimension: 4096
  protocol: 2
