service:
  http_port: 8088
  debug: true
  eino_debug: true
  stream_mode: true
  apmplus_app_key: ""
  apmplus_region: "cn-beijing"
  langfuse_public_key: ""
  langfuse_secret_key: ""
lark:
  app_id:
  app_secret:
llm:
  base_url:
  model:
  api_key:
embed:
  base_url:
  api_key:
  model:
indexer:
  redis:
    addr: "localhost:6379"
    pwd: ""
    index_prefix: "aino_doc:"
    index_name: "vector_index"
    protocol: 2
  milvus:
    addr: "localhost:19530"
    user: ""
    pwd: ""
    db_name: "aino"
    collection: "doc"